theme: jekyll-theme-cayman
title: CV ðŸš€
description: "{{FULL_NAME}}'s CV"
url: "{{URL}}"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - SETUP.md
  - setup.py
  - cv-prompt.txt
  - "*.pdf"
